package mwe.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Collection = 0;
  public static final int Element = 1;
  public static final int ElementReference = 2;
  public static final int ElementWithData = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xeef61dc3149546d5L, 0x88b81405dbdadb08L);
    builder.put(0x8756ce0147f7035L, Collection);
    builder.put(0x8756ce0147dc42aL, Element);
    builder.put(0x8756ce0147f6607L, ElementReference);
    builder.put(0x8756ce0147fa97aL, ElementWithData);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
