package mwe.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCollection = createDescriptorForCollection();
  /*package*/ final ConceptDescriptor myConceptElement = createDescriptorForElement();
  /*package*/ final ConceptDescriptor myConceptElementReference = createDescriptorForElementReference();
  /*package*/ final ConceptDescriptor myConceptElementWithData = createDescriptorForElementWithData();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCollection, myConceptElement, myConceptElementReference, myConceptElementWithData);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Collection:
        return myConceptCollection;
      case LanguageConceptSwitch.Element:
        return myConceptElement;
      case LanguageConceptSwitch.ElementReference:
        return myConceptElementReference;
      case LanguageConceptSwitch.ElementWithData:
        return myConceptElementWithData;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCollection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mwe", "Collection", 0xeef61dc3149546d5L, 0x88b81405dbdadb08L, 0x8756ce0147f7035L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:756be642-0c5d-4307-a4e6-7a87570d1744(mwe.structure)/609513034250940469");
    b.version(3);
    b.aggregate("elements", 0x8756ce0147f7720L).target(0xeef61dc3149546d5L, 0x88b81405dbdadb08L, 0x8756ce0147f6607L).optional(true).ordered(true).multiple(true).origin("609513034250942240").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mwe", "Element", 0xeef61dc3149546d5L, 0x88b81405dbdadb08L, 0x8756ce0147dc42aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:756be642-0c5d-4307-a4e6-7a87570d1744(mwe.structure)/609513034250830890");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mwe", "ElementReference", 0xeef61dc3149546d5L, 0x88b81405dbdadb08L, 0x8756ce0147f6607L);
    b.class_(false, false, false);
    b.origin("r:756be642-0c5d-4307-a4e6-7a87570d1744(mwe.structure)/609513034250937863");
    b.version(3);
    b.property("multiplicity", 0x8756ce0147f6962L).type(PrimitiveTypeId.INTEGER).origin("609513034250938722").done();
    b.associate("element", 0x8756ce0147f6c8aL).target(0xeef61dc3149546d5L, 0x88b81405dbdadb08L, 0x8756ce0147dc42aL).optional(false).origin("609513034250939530").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementWithData() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mwe", "ElementWithData", 0xeef61dc3149546d5L, 0x88b81405dbdadb08L, 0x8756ce0147fa97aL);
    b.class_(false, false, true);
    // extends: mwe.structure.Element
    b.super_(0xeef61dc3149546d5L, 0x88b81405dbdadb08L, 0x8756ce0147dc42aL);
    b.origin("r:756be642-0c5d-4307-a4e6-7a87570d1744(mwe.structure)/609513034250955130");
    b.version(3);
    b.property("data", 0x8756ce0147fb1e9L).type(PrimitiveTypeId.STRING).origin("609513034250957289").done();
    return b.create();
  }
}
