package mwe.generator;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.TemplateModuleInterpreted2;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.smodel.language.LanguageRuntime;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import mwe.generator.templates.QueriesGenerated;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Arrays;
import jetbrains.mps.generator.runtime.TemplateMappingPriorityRule;
import jetbrains.mps.generator.runtime.TemplateUtil;

public class Generator extends TemplateModuleInterpreted2 {

  public Generator(LanguageRegistry languageRegistry, LanguageRuntime sourceLanguage, jetbrains.mps.smodel.Generator generator) {
    super(languageRegistry, sourceLanguage, generator);
  }

  @NotNull
  @Override
  public SModuleReference getModuleReference() {
    return PersistenceFacade.getInstance().createModuleReference("b5d31ba7-96ff-4980-b497-06b89d076f40(mwe.generator)");
  }

  @Override
  protected void fillTemplateModels(TemplateModuleInterpreted2.TemplateModels models) {
    models.templates("r:9e8bd7af-c2f6-4964-bc8a-3b6ed43b26b8", QueriesGenerated.class);
  }


  @Override
  public Collection<SLanguage> getTargetLanguages() {
    SLanguage[] rv = new SLanguage[1];
    rv[0] = MetaAdapterFactory.getLanguage(0xeef61dc3149546d5L, 0x88b81405dbdadb08L, "mwe");
    return Arrays.asList(rv);
  }

  @Override
  public Collection<TemplateMappingPriorityRule> getPriorities() {
    return TemplateUtil.asCollection(TemplateUtil.createStrictlyBeforeRule(TemplateUtil.createRefExternal("b5d31ba7-96ff-4980-b497-06b89d076f40(mwe.generator)", TemplateUtil.createRefNormal("r:9e8bd7af-c2f6-4964-bc8a-3b6ed43b26b8(mwe.generator.templates@generator)", "609513034250830884", "main")), TemplateUtil.createRefExternal("b5d31ba7-96ff-4980-b497-06b89d076f40(mwe.generator)", TemplateUtil.createRefNormal("r:9e8bd7af-c2f6-4964-bc8a-3b6ed43b26b8(mwe.generator.templates@generator)", "609513034251009521", "fix_reference"))));
  }
}
